name: Release - CI
on:
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Build, Test, Deploy
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
    steps:
    - name: Get the version
      id: get_version
      run: |
        arrTag=(${GITHUB_REF//\// })
        VERSION="4.0.4"
        VERSION="${VERSION//v}"
        echo VERSION:${VERSION}
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "15"
    - uses: ./.github/actions/setup-dotnet
    - name: Set build number 
      if: matrix.os == 'ubuntu-24.04'
      run: echo "BuildNumber=$(( $GITHUB_RUN_NUMBER + 15471 ))" >> $GITHUB_ENV
    - name: Build
      # NuGetAudit is intentionally not disabled here like it is for other CI builds, because we need to address any
      # vulnerable packages before releasing a new version.
      run: |
        dotnet build -c Release /p:TreatWarningsAsErrors=true /p:RunAnalyzers=true -p:Version=${{ steps.get_version.outputs.VERSION }}
    - name: Deploy release NuGet packages to Azure Artifacts
      if: matrix.os == 'ubuntu-24.04'
      env:
        AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        dotnet pack -c Release --no-build -p:Version=${{ steps.get_version.outputs.VERSION }} -p:TreatWarningsAsErrors=false
        dotnet nuget add source "https://pkgs.dev.azure.com/TopSoft365/ArCa/_packaging/ArCaFeed/nuget/v3/index.json" --name "AzureArtifacts" --username "anything" --password "${AZURE_DEVOPS_EXT_PAT}" --store-password-in-clear-text
        dotnet nuget push './src/**/*.nupkg' --source "AzureArtifacts" --api-key "AzureDevOps" --skip-duplicate
